### ISSUE TITLE
Handling proxies

### ISSUE THREAD

**Issue by realies** [access-watch/access-watch#100]
When inspecting traffic that has gone through a proxy service such as Cloudflare it is not possible to view the real user's IP address. Custom log configurations for services could be made to contain the `x-forwarded-for` header value, although this has to be handled by `access-watch` as well. Is there a recommended configuration for including the real user's IP within the statistics?

**Comment by znarf** [comment]
There is proxy support by default and Cloudflare is one of the supported use case. The `x-forwarded-for` header needs to be available though.

What kind of input configuration are you using?

**Comment by realies** [comment]
Perhaps the logging format of Nginx needs changing? Using an example from the docs:

```
const defaultInput = input.file.create({
  name: 'default',
  path: '/logs/access.log',
  parse: format.nginx.parser({format: format.nginx.formats.combined})
})
```

**Comment by znarf** [comment]
I would then recommend to tweak your Nginx log format to include the `X-Forwarded-For`.

Example modifying the 'combined' log format:

```
log_format combined_with_x_forwarded_for '$remote_addr - $remote_user [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'
access_log /logs/access.log combined_with_x_forwarded_for;
```

Or modifying the 'access_watch_combined' log format:

```
log_format access_watch_combined_with_x_forwarded_for '$remote_addr - $remote_user [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent" "$http_accept" "$http_accept_charset" "$http_accept_encoding" "$http_accept_language" "$http_connection" "$http_dnt" "$http_from" "$http_host" "$http_x_forwarded_for"'
access_log /logs/access.log access_watch_combined_with_x_forwarded_for;
```

You need to update Access Watch configuration to support the new format (copy and paste the format used in Nginx configuration)

```javascript
const defaultInput = input.file.create({
  path: '/logs/access.log',
  parse: format.nginx.parser({
    format: '$remote_addr - $remote_user [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent" "$http_accept" "$http_accept_charset" "$http_accept_encoding" "$http_accept_language" "$http_connection" "$http_dnt" "$http_from" "$http_host" "$http_x_forwarded_for"'
  })
})
```

**Comment by realies** [comment]
Great to see this working! Would be great to have this in the user guide.

**Comment by znarf** [comment]
Let's integrate that in the Nginx guide (and Apache?) and close this issue.
