### ISSUE TITLE
Reload configuration

### ISSUE THREAD

**Issue by realies** [access-watch/access-watch#101]
It would be great if Access Watch is listening for changes in the loaded configuration file and reloading it appropriately.

**Comment by znarf** [comment]
At this stage, we're not gonna provide 'hot reloading' or 'watching' for the configuration.

To have the process watch changes to the configuration file, we recommend using something like [pm2](http://pm2.keymetrics.io/docs/usage/watch-and-restart/).

We do use `pm2` for all our own deployments. But not the `watch` feature so far!
