### ISSUE TITLE
Ability to tweak session GC configuration (now 1h)

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#106]
'Sessions' (Address and Robots) are currently garbage collected after 1 hour of inactivity.

Let's make that configurable, maybe switch the default to 24 hours of inactivity.

**Comment by realies** [comment]
![screenshot-2018-1-8 access watch dashboard](https://user-images.githubusercontent.com/5107843/34672644-2cefb66e-f477-11e7-8cd7-28531d135d0e.png)

![screenshot-2018-1-8 access watch dashboard 1](https://user-images.githubusercontent.com/5107843/34672647-2f4ee9c0-f477-11e7-8260-ed3d6339b156.png)

![screenshot-2018-1-8 access watch dashboard 2](https://user-images.githubusercontent.com/5107843/34672860-fd1238bc-f477-11e7-83a4-417916c5f289.png)

![screenshot-2018-1-8 access watch dashboard 3](https://user-images.githubusercontent.com/5107843/34672668-480c697e-f477-11e7-87d6-ccb005397955.png)

**Comment by znarf** [comment]
@realies yes, it's only work in progress in the configuration branch, but should soon be: https://github.com/access-watch/access-watch/tree/configuration

**Comment by znarf** [comment]
See https://github.com/access-watch/access-watch/blob/master/docs/configuration.md for documentation.
