### ISSUE TITLE
Memory Logs retention should be duration based

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#166]

**Comment by jduthon** [comment]
Are we sure about this one?
I see pros/cons of both of them.

The obvious pro of duration based is that it is nicer to use / more predictable.

The pro of a number is that it will work for any configuration : 
- If you have lot of traffic, you will have very recent traffic only BUT you will never destroy your instance with too many logs
- If you have a small amount of traffic, you will benefit from a lot of logs stored.

With a duration based retention, we will have to make a choice between the two and leave it to user's configuration to make a better choice if he is in the other case.

**Comment by znarf** [comment]
No, we're not sure and you nailed the reasons.

**Comment by znarf** [comment]
Let's keep it like it is.
