### ISSUE TITLE
Update /metrics endpoint

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#18]
- [ ] the date exposed in the JSON should be usable in the URL parameters (_start_ and _end_)
- [ ] the date should ba a unix timestamp with second precision
- [ ] the response should be an array, it should be ordered.

 ~~I suggest:~~

-  ~~the URL parameter to be anything that can be parsed by the javascript Date constructor (so a timestamp in ms in regular use case).~~
 - ~~to expose the date as a timestamp in ms.~~

Optionally:

- ease debugging, with a parameter that turns dates to  ISO 8601

**Comment by benfle** [comment]
I agree that it is important that the API be symmetrical. Same date format in input and output. 

I don't think we should have multiple ways to specify the time parameters. It is unnecessary complexity. Moreover, the metrics module use timestamps in seconds everywhere. So I think we should stick to timestamps in seconds in the interface.

As for the option to return ISO dates, I'm fine with that if we make it clear in the design of the API that it is a debug mode and not something to use in production.

For the array, definitely yes.

**Comment by znarf** [comment]
Ok, we stick and enforce timestamp in seconds in the response and in the URL parameters.

**Comment by znarf** [comment]
I reverted the changes, the /metrics and /activity endpoint were broken.

There is some ongoing changes in UI to get rid of those and use the /metrics/request endpoint, but they're not ready yet.

**Comment by znarf** [comment]
I reopened a PR there:
https://github.com/access-watch/access-watch/pull/27
