### ISSUE TITLE
Advanced Addresses handling

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#188]
This is a meta-ticket to cover multiple improvements.

- ability to block/unblock from the list
- ability to whitelist/unwhitelist from the list
- maybe remove, `as number` and `network name` to make space available
- ability to edit the label of an address (useful to take notes, and/or if the hostname doesn't speak for itself)

**Comment by jduthon** [comment]
Block/Unblock and Whitelist/Unwhitelist sounds good.

The ability to edit the label is kind of problematic IMO, as addresses are stored in sessions which are possibly garbage collected at some point, it could mean that you will take time to rename addresses to actually see your precious labels gone at some point no?
Or we should try to find a mechanism to store labels separately and apply them dynamically?
