### ISSUE TITLE
Rules.type filter not working in Robots/Addresses

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#204]

**Comment by jduthon** [comment]
Not working with ES as `rule.type` does not make any sense as a filter in the logs stored in ES.
I believe we need to remove the filter before looking up inside the DB, and filter afterwards the session once we have acquired the infos about them being blocked or not.
It still leaves the problem of the limit not being precise anymore... (Like requesting 50 sessions from ES, then filtering them out and maybe keeping only 10)
I will try to come up with a smart solution.

**Comment by jduthon** [comment]
Small thing we can eventually think of if it makes sense, with the fix in place it becomes possible (and relatively simple) to add the `rule.type` filtering inside of `/requests`

**Comment by znarf** [comment]
@jduthon I'm up for it (`rule.type` filtering inside of `/requests`)

**Comment by jduthon** [comment]
Ok, do we make it part of this branch?
