### ISSUE TITLE
Sub-Request input

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#46]
Create a new input that can be used in combination with such Nginx configuration:
https://github.com/lebinh/nginx-conf#sub-request-upon-completion

**Comment by benfle** [comment]
The input would be a http server that translates all http requests into a log object if I understand the setup correctly.

Some questions:
* How does the HTTP request look from the AW server's perspective? Identical? Extra HTTP headers?
* Do we lose the client IP?
* The response status code becomes optional (?)

**Comment by znarf** [comment]
I implemented a first version quickly:
https://github.com/access-watch/access-watch/tree/replay-input

- the implementor should add extra headers as needed to recompose the original HTTP request, such as X-Forwarded-For, X-Real-Ip, X-Forwarded-Host.
- the IP should then be passed through X-Forwarded-For, X-Real-Ip or other custom header
- the status code is lost, unless it's passed with a custom header

Nginx configuration:

```
    location / {
        post_action @replay;
    }

    location @replay {
        internal;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://0.0.0.0:4001;
    }
```

**Comment by znarf** [comment]
Let's not have that in core for now. If someone ask for it, we can give them directions to do it themselves.
