### ISSUE TITLE
Set the `end` parameter to `now()` if not specified in the API

### ISSUE THREAD

**Issue by benfle** [access-watch/access-watch#51]

**Comment by znarf** [comment]
The fix was breaking metrics. Let's check.

**Comment by benfle** [comment]
That is very strange. Are you sure it is this specific change that caused the bug?

**Comment by jduthon** [comment]
Yes.
Seems like the problem is happening when : 
No end is specified and the step is rather big.
So it's surely something between step and end...
With smaller steps (especially with `1`) it always works

**Comment by benfle** [comment]
Ok thanks for the clarification.
