### ISSUE TITLE
Get rid of the dashboard HTTP API

### ISSUE THREAD

**Issue by benfle** [access-watch/access-watch#52]
* Ensure the `/robots` endpoint can be replaced by `/sessions/:type` endpoint
* Create a `/sessions/:type/:id` endpoint
* Get rid of the `/logs` endpoint

We will deal with websocket later.

**Comment by benfle** [comment]
@jduthon The branch `issue-52` contains the work for this issue.

For the `/robots` endpoint you will have to use `/sessions/:type` instead. Changes:

1. We  return sorted array instead of object with `sessions` attribute
2. We return the average speed per minute for the last 15 minutes instead of the speed object (per_second, per_minute)

You should be able to replace the `/session/:id` endpoint by `/sessions/:type/:id` without any impact.

**Comment by znarf** [comment]
It's merged.

**Comment by benfle** [comment]
@znarf @jduthon Did you do the work on the client side to use the new API?

**Comment by jduthon** [comment]
Now yes :)
