### ISSUE TITLE
Rules endpoint should handle errors

### ISSUE THREAD

**Issue by jduthon** [access-watch/access-watch#54]
The rules endpoint is returning ok no matter what happened with the provided rule.

Then if a rule is incorrect, it will crash later on when trying to use it.

**Comment by benfle** [comment]
Are you asking to validate that the rule is well-formed at creation time? So for example ensure that the IP is a real IP address so it doesn't crash later?

Another way to do it would be to catch rules that throws, report the error, and do not apply them for the next logs so it doesn't constantly crash.

**Comment by jduthon** [comment]
Well I didn't think of verifying the IP address.
But I had some problems as I was sending data as `form-encoded`, not `json` which resulted in the backend trying to add a rule which was `{}` and the adding part in that case goes well.
But then it crashes later on.
So I believe we need some minimal check on what has been sent (so verifying it has a `conditions` which has an `array` of `{type}` for now would already be great).
Then maybe we want to know the possible type and have validator for each of them (so the `ip` one wants to verify it has an `ip` property and that it is a string).
Right?

If you want I can do that later if you have a lot on your plate.

And then yes, I would say we need to not crash on incorrect rules, but at least with some validation before hands I believe we should not have incorrect rules anymore?

**Comment by benfle** [comment]
Ok I see what you mean now. Let's keep the issue open to implement the validation of the rules on the endpoint.

1. Validate that the rule is well-formed
2. Validate that the condition is well-formed

I will open another issue for the handling of matching errors.
