### ISSUE TITLE
Init script

### ISSUE THREAD

**Issue by szepeviktor** [access-watch/access-watch#58]
Please consider adding

- SysVinit
- upstart
- systemd

scripts.
Thanks.

**Comment by znarf** [comment]
@szepeviktor we will not provide that for now, only in the future when we will have packages for popular linux distributions.

For the time being, we recommend using pm2, a great node process manager. Usage:

```
# Install pm2
npm install -g pm2
# Plug pm2 on startup with the system
pm2 startup
# Start Access Watch with pm2
pm2 start ~/access-watch/index.js --name "access-watch" -- ~/access-watch/config/example.js
# Save pm2 state, the Access Watch process will be restarted with pm2
pm2 save
```

**Comment by szepeviktor** [comment]
Thank you.
