### ISSUE TITLE
Connection to access.watch

### ISSUE THREAD

**Issue by szepeviktor** [access-watch/access-watch#59]
Is this project somehow connected to the Access Watch database?
Could we look up IP reputation?

**Comment by znarf** [comment]
@szepeviktor Yes, the Access Watch processor is connected by default to the Access Watch database. 

We just released a new version that is displaying the IP addresses in real time, reputation is included.

Is that working for you?

**Comment by szepeviktor** [comment]
Thanks.

I am in the process of connecting my webserver with access-watch.
