### ISSUE TITLE
Session speeds 0 when instance just started

### ISSUE THREAD

**Issue by jduthon** [access-watch/access-watch#64]
When starting an instance, all the speeds return for a particular session except the current one are set to 0.
Would there be a way on the processor side to not return those "fake" 0 ?
Or should I just cut them off myself with the `start` property?

**Comment by benfle** [comment]
I'm not sure to understand why it would be a problem. How do you use those 15 numbers?

**Comment by jduthon** [comment]
I am computing an average speed over the 15 minutes with them.
And I think it's technically misleading as their speed at this moment is not really 0, it is just unknown as the instance was just started.
