### ISSUE TITLE
Metadata for IP addresses in Rules

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#66]
We need an easy way to get data such as hostname and country_code when presenting the IP address in the Rules screen.

We would need the same when doing robots rules/blocking.

**Comment by benfle** [comment]
Working on this. Keep in mind that the dashboard should also work if the data is not available.

**Comment by benfle** [comment]
Do we really need this address data?

When we will create a condition on a robot, we can copy the whole robot object to the condition in the rule.

For addresses, we will need to get this data out of a log that match the rule. It also means we won't have the data until the first log is seen by the rule.

And we also need to be able to function without this augmented data.

This adds a lot of complexity and I am not sure to see the value of it.

**Comment by znarf** [comment]
When I see it, it's clear for me it doesn't make sense to display an IP address without any metadata and context. As a user, I need to understand a bit what is behind this thing.

![screen shot 2017-11-30 at 21 37 31](https://user-images.githubusercontent.com/806/33453641-b535975c-d616-11e7-8319-eefdbed062e6.png)

We have an API available to cheaply augment data on the fly if we need to, from the client side or from the server side.

**Comment by jduthon** [comment]
We could also add the metadata when blocking ( and in such case we already have the information available at the moment of blocking).
Though rules will become pretty complex very quickly I believe as it represents mixed data.
I notably for now reduce complexity of the conditions by only displaying one of them, but for more complex stuff we will need to think more thoroughly about it.

**Comment by benfle** [comment]
Done in https://github.com/access-watch/access-watch/pull/91

**Comment by znarf** [comment]
Let's update the UI and we can close this issue.
