### ISSUE TITLE
Replace robots/addresses panels by a single panel of active "entities"

### ISSUE THREAD

**Issue by benfle** [access-watch/access-watch#72]
This panel would show the active entities on the website during the last 24h. 

This is relatively easy to implement on the backend. For each type of entity we need to create a set of sessions that will keep track of the activity of the entities. "Sessions" might not be the best term for the user-interface however.

This panel also allows the user to block a given entity. So an entity is everything that the user might be interested in blocking. We would support the following for now:

* Robot
* Address
* User-Agent

**Comment by znarf** [comment]
We're not gonna do that but simply iterate on what we have for now (Addresses + Robots).
