### ISSUE TITLE
Save state on shutdown. Reload it on start.

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#73]
Users will want to update the software and keep the data.

Let's have a simple way to dump metrics/sessions and reload it.

**Comment by znarf** [comment]
https://github.com/access-watch/access-watch/pull/74

**Comment by realies** [comment]
@znarf, where is data being kept? Still can't get it to reload when restarting `access-watch`.

**Comment by znarf** [comment]
@realies the data is kept in the `/data/` directory.
