### ISSUE TITLE
No 0 data point in session activity

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#80]
We don't see any 0 data point in session activity right now.

That's likely a bug to investigate!

**Comment by benfle** [comment]
I don't understand what that means.

**Comment by znarf** [comment]
It means we never see a data point with '0 requests' in activity objects returned by the session endpoint. If an address is having intermittent activity, I would expect to have something like: `[5, 0, 3, 2, 0, 3]` while today we never see that.

**Comment by jduthon** [comment]
I was working on this as you asked med @znarf x)

Problem is coming from the filtering of undefined in session.js => Speed class => compute.

I think you/we need to keep in memory the first time an address had a hit, then use this to know how many data points to return.

Something like this : 

```
class Speed {
  constructor (size) {
    this.size = size
    this.counters = {}
  }

  hit (time) {
    const idx = time - time % 60
    if (!this.firstIndex) {
      this.firstIndex = idx
    }
    if (this.counters[idx] === undefined) {
      this.counters[idx] = 1
    } else {
      this.counters[idx]++
    }
    return this
  }

  compute () {
    const time = now()
    const currentMinute = time - time % 60
    return Range(0, Math.min((currentMinute - (this.firstIndex || currentMinute)) / 60, this.size))
      .map(n => {
        return this.counters[currentMinute - n * 60] || 0
      })
  }
}
```
