### ISSUE TITLE
Count should be 24 hours count

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#83]
Currently, for the user, the definition of 'count' is unclear, and on the backend side, it can actually be counting for an unlimited period.

Let's limit that to 24 hours.

**Comment by benfle** [comment]
I propose to store the number of requests per hour for the last 24 hours and return them in speed like this:

```
{
  speed: {
    per_minute: [5, 5, 5...],
    per_hour: [300, 300, 300...]
  }
}
```

**Comment by benfle** [comment]
Or:

```
{
  metrics: {
    per_minute: [
      [1512661920 5],
      [1512661860 5],
      ...
    ],
  per_hour: [
      [1512658800 300],
      [1512655200 300],
      ...
    ]
  }
}
```

**Comment by benfle** [comment]
@znarf @jduthon Feedback on this?

**Comment by jduthon** [comment]
This would be for the sessions right?
I am not against it, seems clear and might be useful.
Will have to make some modifications on the front-end to take care of it but nothing crazy :)

**Comment by benfle** [comment]
@jduthon Yes, for the sessions.

**Comment by znarf** [comment]
I'm good. Only annoyance is the breaking change in the API format, but that's all.

**Comment by benfle** [comment]
Done in https://github.com/access-watch/access-watch/pull/91
