### ISSUE TITLE
Have a CLI pipeline.status interface

### ISSUE THREAD

**Issue by jduthon** [access-watch/access-watch#89]
Typically right now the `pipeline.status` is only used for the monitoring HTTP endpoint.
It would be great if it could also write to the regular console as it goes, so the user can always know what is going on to an extend on the CLI without the need to fire up the interface.

**Comment by benfle** [comment]
@znarf, @jduthon Now that I'm rereading the issue. Is the goal to monitor the pipeline without the web UI? If it is then maybe we should write the input rates in the console every x minutes too? What do you think?

**Comment by jduthon** [comment]
Hmmm, my base idea was to avoid the multiple console.logs inside each inputs and delegate that to the `pipeline.status`.
Though it could also be interesting to be able to have a CLI monitoring.

**Comment by benfle** [comment]
I'm fine with keeping it simple for now. I just wanted to throw the idea out there while we were on the topic.
